spring:
  application:
    name: carnaboard

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  datasource:
    driver-class-name: org.sqlite.JDBC

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
  info:
    title: My Custom API Title
    version: 1.0.0
    description: This is my custom API documentation.
    contact: name=API Support Team
  show-actuator: true

app:
  latest:
    version: ${APP_LATEST_VERSION:1.0.0}
    url: ${APP_LATEST_URL:https://github.com/GustavoMinghini/carnaboardfront/releases/download/v1.0.0/app-release.apk}




